import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/providers/query-provider";
import { Toaster } from "@/components/ui/toaster";
import { getServerSession } from "next-auth";
import AuthProvider from "@/providers/auth-provider";
import { authOptions } from "@/lib/auth/authOption";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  // console.log(session);
  return (
    <html lang="en">
      <head>
        <meta name="cryptomus" content="8ad80688" />
      </head>
      <body className={inter.className}>
        <QueryProvider>
          <AuthProvider session={session}>{children}</AuthProvider>
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
